### ISSUE TITLE
[Fabric] Crashes during datagen

### ISSUE THREAD

**Issue by NemoNotFound** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#157]
**Describe the bug**
I want to create recipes of  wood from region unexplored for my mod with datagen. To do that I add the mod dependencies over cursemaven. I am using the latest Regions unexplored and Terrablender version for Minecraft 1.20.4. Is this an issue on your side? I saw something similar for server crashes, but it didn't help me. Or is it an issue on my side? Because I can play them over curseforge, but when I want to do it over my IDE it fails.

If it's an issue on my side, I appologize :D

**Crash Logs**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terrablender'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.1.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[minecraft-merged-7c97a1825d-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class io.github.uhq_games.regions_unexplored.RegionsUnexplored
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Class.java:495) ~[?:?]
		at java.lang.Class.forName(Class.java:474) ~[?:?]
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.1.jar:?]
		at net.minecraft.server.Main.main(Main.java:109) ~[minecraft-merged-7c97a1825d-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: me/lortseam/completeconfig/data/Config [in thread "main"]
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
		at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		at io.github.uhq_games.regions_unexplored.RegionsUnexplored.<clinit>(RegionsUnexplored.java:45) ~[regions-unexplored-659110-4968691.jar:?]
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Class.java:495) ~[?:?]
		at java.lang.Class.forName(Class.java:474) ~[?:?]
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.1.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.1.jar:?]
		at terrablender.core.TerraBlenderFabric.lambda$onInitialize$0(TerraBlenderFabric.java:35) ~[terrablender-fabric-565956-5068224.jar:?]
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
		at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:34) ~[terrablender-fabric-565956-5068224.jar:?]
		... 7 more
Caused by: java.lang.NoClassDefFoundError: me/lortseam/completeconfig/data/Config
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at io.github.uhq_games.regions_unexplored.RegionsUnexplored.<clinit>(RegionsUnexplored.java:45) ~[regions-unexplored-659110-4968691.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.1.jar:?]
	at terrablender.core.TerraBlenderFabric.lambda$onInitialize$0(TerraBlenderFabric.java:35) ~[terrablender-fabric-565956-5068224.jar:3.3.0.12]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:34) ~[terrablender-fabric-565956-5068224.jar:3.3.0.12]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: me.lortseam.completeconfig.data.Config
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at io.github.uhq_games.regions_unexplored.RegionsUnexplored.<clinit>(RegionsUnexplored.java:45) ~[regions-unexplored-659110-4968691.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.1.jar:?]
	at terrablender.core.TerraBlenderFabric.lambda$onInitialize$0(TerraBlenderFabric.java:35) ~[terrablender-fabric-565956-5068224.jar:3.3.0.12]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:34) ~[terrablender-fabric-565956-5068224.jar:3.3.0.12]
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: me/lortseam/completeconfig/data/Config [in thread "main"]

	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.1.jar:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: me/lortseam/completeconfig/data/Config

Caused by: java.lang.ClassNotFoundException: me.lortseam.completeconfig.data.Config
```

**How To Reproduce**
Steps to reproduce the bug:
- add regions unexplored and terrablender to dependencies.
- run Minecraft or datagen

**Version**
Minecraft Version: 1.20.4

Modloader Version: 0.15.10

Mod Version: fabric - 0.5.5

**Comment by KirboSoftware** [comment]
You would need to add complete config in dev 👍, we normally JiJ it into our mod, but since it's getting no longer supported and how JiJ kinda makes you add all deps, it's more an oversight than anything sadly.

**Comment by NemoNotFound** [comment]
I also tried that, but it didn't work. I got the same config. So this should be added right?
https://www.curseforge.com/minecraft/mc-mods/completeconfig

**Comment by NemoNotFound** [comment]
Perhaps I'm using a wrong version? I tried using the latest version for 1.20.4:

`modImplementation "curse.maven:completeconfig-381257:4993047"`

**Comment by KirboSoftware** [comment]
that didn't work even with completeconfig indev?

**Comment by NemoNotFound** [comment]
Unfortunately not. I have these in my dependencies:

```
modImplementation "curse.maven:terrablender-fabric-565956:5068224"
modImplementation "curse.maven:regions-unexplored-659110:4968691"
modImplementation "curse.maven:completeconfig-381257:4993047"
```

Which version of completeconfig is used by Regions Unexplored?

Edit:
I also tried to add it like described here: https://github.com/Lortseam/completeconfig/wiki/Setup

Now I get new errors:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'regions_unexplored'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[minecraft-merged-7c97a1825d-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2368
		at io.github.uhq_games.regions_unexplored.data.worldgen.biome.surface.RuNetherSurfaceBuilder.<clinit>(RuNetherSurfaceBuilder.java:17) ~[regions-unexplored-659110-4968691.jar:?]
		at io.github.uhq_games.regions_unexplored.registry.BiomeRegistry.setupTerrablender(BiomeRegistry.java:33) ~[regions-unexplored-659110-4968691.jar:?]
		at io.github.uhq_games.regions_unexplored.RegionsUnexplored.onTerraBlenderInitialized(RegionsUnexplored.java:71) ~[regions-unexplored-659110-4968691.jar:?]
		at terrablender.core.TerraBlenderFabric.lambda$onInitialize$0(TerraBlenderFabric.java:36) ~[terrablender-fabric-565956-5068224.jar:3.3.0.12]
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
		at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:34) ~[terrablender-fabric-565956-5068224.jar:3.3.0.12]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.10.jar:?]
		at net.minecraft.server.Main.main(Main.java:109) ~[minecraft-merged-7c97a1825d-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
		at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2368
		at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		... 13 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2368
	at io.github.uhq_games.regions_unexplored.world.level.feature.AshVentFeature.<clinit>(AshVentFeature.java:19) ~[regions-unexplored-659110-4968691.jar:?]
	at io.github.uhq_games.regions_unexplored.registry.FeatureRegistry.<clinit>(FeatureRegistry.java:57) ~[regions-unexplored-659110-4968691.jar:?]
	at io.github.uhq_games.regions_unexplored.RegionsUnexplored.onInitialize(RegionsUnexplored.java:56) ~[regions-unexplored-659110-4968691.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2368
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at io.github.uhq_games.regions_unexplored.world.level.feature.AshVentFeature.<clinit>(AshVentFeature.java:19) ~[regions-unexplored-659110-4968691.jar:?]
	at io.github.uhq_games.regions_unexplored.registry.FeatureRegistry.<clinit>(FeatureRegistry.java:57) ~[regions-unexplored-659110-4968691.jar:?]
	at io.github.uhq_games.regions_unexplored.RegionsUnexplored.onInitialize(RegionsUnexplored.java:56) ~[regions-unexplored-659110-4968691.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	... 6 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2368

Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2368

Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2368
```

**Comment by KirboSoftware** [comment]
Why is the grass block class not there? 😕 Have you tried closing your IDE and relaunching it (some weird caching issue)

**Comment by NemoNotFound** [comment]
I did, but it didn't help :(
Btw how did you get the actual class from the intermediate name?

**Comment by KirboSoftware** [comment]
I used linkie! 

Here is the query I did:
https://linkie.shedaniel.dev/mappings?namespace=yarn&version=1.20.1&search=net.minecraft.class_2368&translateMode=ns&translateAs=mojang_raw

Could I see the project where this would be? So I could perhaps trouble shoot faster

**Comment by NemoNotFound** [comment]
Sure, let me commit my changes, then I'll send the link here. It's not a mod, just something I use to generate the recipes for my mod.

And thank you for the link! I didn't know of this, very convenient :D

**Comment by NemoNotFound** [comment]
Here the link to the branch: https://github.com/NemoNotFound/NemosWoodcutterRecipeGenerator/tree/1.20.4

Edit: There is also BiomesOPlenty included, but I also tried with only having RegionsUnexplored in my project and it still returned the same error

**Comment by KirboSoftware** [comment]
Hey, I see you've made it work. I kinda forgot we used the `base` implementation and not the cursemaven approach. My apologies 👍

**Comment by NemoNotFound** [comment]
Wait, I didn't get it to work xD
After I added the base implementation I got this error with the grass block. Or were you able to generate recipes with my branch?

**Comment by KirboSoftware** [comment]
Oh no, I looked at your branch of stuff that you implemented the recipes, I thought stuff was working. Lemme see on my end 👍

**Comment by NemoNotFound** [comment]
Ahh, that were other recipes :D
Thanks a lot! I have no clue at all what's wrong here xD

**Comment by KirboSoftware** [comment]
Found the issue 👍 you use the 1.20.2 version of regions while there is an 1.20,4 version out.

**Comment by NemoNotFound** [comment]
Oh, I might have changed the version to 1.20.2 after 1.20.4 failed for me and forgot to revert it

**Comment by NemoNotFound** [comment]
It works now! Thanks a lot and sorry for this stupid mistake at the end xD
Fortunately it wasn't the initial error, so it was not that dumb haha
