### ISSUE TITLE
Bug Report: Signs cause crash when placed

### ISSUE THREAD

**Issue by Kellogs62** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#191]
Whenever a sign of any material of the mod is placed it crash the game, in singleplayer and in multiplayer.

**Crash Logs**
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24145(net.minecraft.class_4597, java.util.function.Function)" because "$$7" is null
	at net.minecraft.class_837.method_45800(class_837.java:101)
	at net.minecraft.class_837.method_49920(class_837.java:81)
	at net.minecraft.class_837.method_23083(class_837.java:66)
	at net.minecraft.class_837.method_3569(class_837.java:41)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.minecraft.class_761.method_22710(class_761.java:1114)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Block Entity Details --
Details:
	Name: regions_unexplored:sign_block_entity // net.regions_unexplored.block.entity.custom.RuSignBlockEntity
	Block: Block{regions_unexplored:maple_wall_sign}[facing=west,waterlogged=false]
	Block location: World: (10606,154,10614), Section: (at 14,10,6 in 662,9,663; chunk contains blocks 10592,-64,10608 to 10607,319,10623), Region: (20,20; contains chunks 640,640 to 671,671, blocks 10240,-64,10240 to 10751,319,10751)
	Block: Block{regions_unexplored:maple_wall_sign}[facing=west,waterlogged=false]
	Block location: World: (10606,154,10614), Section: (at 14,10,6 in 662,9,663; chunk contains blocks 10592,-64,10608 to 10607,319,10623), Region: (20,20; contains chunks 640,640 to 671,671, blocks 10240,-64,10240 to 10751,319,10751)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.minecraft.class_761.method_22710(class_761.java:1114)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**How To Reproduce**
Just place a sign

**Version**
Minecraft Version: 1.21

Mod Version: 0.5.6.1+1.21

**Comment by matrixguy69** [comment]
hi same issue any solution ?
