### ISSUE TITLE
Bug Report: crash on new chunk generation

### ISSUE THREAD

**Issue by tekit** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#22]
**Describe the bug**
Minecraft crash on new chunk generation. The world is an old RU world updated to 0.5.0.

**Crash Logs**
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-08-25 10:38:28
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:sparse_jungle]=net.minecraft.class_1959@16dd1c10}, Reference{ResourceKey[minecraft:worldgen/biome / regions_unexplored:rainforest]=net.minecraft.class_1959@6297ef54}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.method_44215(class_2794.java:102)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:288)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.method_12154(class_2806.java:252)
	at net.minecraft.class_3898.method_17225(class_3898.java:684)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.method_44215(class_2794.java:102)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:288)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.method_12154(class_2806.java:252)
	at net.minecraft.class_3898.method_17225(class_3898.java:684)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

-- Chunk to be generated --
Details:
	Location: 72,-53
	Position hash: -227633266616
	Generator: net.minecraft.class_3754@5e238372
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:684)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Wrapped in --
Details:
	Wrapping exception: ~~ERROR~~ CompletionException: net.minecraft.class_148: Exception generating new chunk
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_40376(MinecraftServer.java:729)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4745254856 bytes (4525 MiB) / 12985565184 bytes (12384 MiB) up to 15032385536 bytes (14336 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon RX 5600 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.9001
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 130988.47
	Virtual memory used (MB): 47473.80
	Swap memory total (MB): 65536.00
	Swap memory used (MB): 2007.98
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Version**
Minecraft Version: 1.20.1

Modloader Version: fabric-loader-0.14.22

Mod Version: 0.5.0

**Comment by UHQ-GAMES** [comment]
Thanks! It's a known issue on terraliths side and ive reported it to the Terralith devs!

**Comment by UHQ-GAMES** [comment]
fixed in terralith 2.4.5
