### ISSUE TITLE
[Bug Report] FORGE Worldgen crash when trying to add Croptopia crops to RU biomes

### ISSUE THREAD

**Issue by RechercheRaptor** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#85]
Minecraft version 1.19.2, Forge version 43.3.5.

For some reason configuring Croptopia crops to generate in Regions Unexplored biomes is crashing my game upon world generation, and Regions Unexplored biomes consistently appear in the crash messages. Basically Croptopia crops have a config that lets you add biomes to a list where each crop can spawn, and I thought it would make it feel more immersive to have them spawn in RU biomes and not just vanilla, but oddly that seems to interfere with world generation as a whole somehow.

This is the usual kind of crash message I get:
“The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Feature order
cycle found, involved sources:
[ Reference{ResourceKey[minecraft:worldgen/biome /
regions_unexplored:magnolia_woodland]=net.minecraft.world.level.biome.Biome@1f40f00a},
Reference{ResourceKey[minecraft:worldgen/biome /
minecraft:flower_forest]=net.minecraft.world.level.biome.Biome@2c111956}]"

There's always a Regions Unexplored biome and a minecraft biome mentioned together, usually sparse rainforest & sparse jungle or rainforest & jungle, but in this instance magnolia forest & flower forest. I think I set some Croptopia crops that usually generate in those vanilla biomes to also spawn in the respective RU biomes. I'm submitting the error here because RU biomes are consistently mentioned in all of the worldgen crashes, but if the crash logs show that it's really just from Croptopia I'll submit it to them. When I deleted my Croptopia configs (regenerating them without any RU biomes mentioned) worlds generate just fine again.

The crash messages at one point implicated the Blueprint mod Team Abnormals uses, so I disabled Neapolitan and Blueprint, but I still got a crash during world generation with a chunk exception error about sparse rainforest and sparse jungle. I've included this crash report below.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-12-18 11:50:01
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / regions_unexplored:rainforest]=net.minecraft.world.level.biome.Biome@145bf987}, Reference{ResourceKey[minecraft:worldgen/biome / regions_unexplored:sparse_rainforest]=net.minecraft.world.level.biome.Biome@52fa07e7}]
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223094_(ChunkGenerator.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:397) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223094_(ChunkGenerator.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:397) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
-- Chunk to be generated --
Details:
	Location: 3,-7
	Position hash: -30064771069
	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@9dfd043
Stacktrace:
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23120!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (72,64,-88), Section: (at 8,0,8 in 4,4,-6; chunk contains blocks 64,-64,-96 to 79,319,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:347) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:300) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23240!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 13.2.1
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 533198512 bytes (508 MiB) / 2283798528 bytes (2178 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 12288.00
	Virtual memory used (MB): 9535.03
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 3075.06
	JVM Flags: 2 total; -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:tht, mod:habitat, mod:jei (incompatible), mod:galosphere (incompatible), mod:paragon, mod:structorytowers, mod:waystones (incompatible), mod:badpackets (incompatible), mod:mixinextras (incompatible), mod:gemsnjewels, mod:twigs (incompatible), mod:starlight (incompatible), mod:molten_vents (incompatible), mod:bygonenether, mod:balm (incompatible), mod:memoryleakfix (incompatible), mod:forge, mod:ctov (incompatible), mod:supplementaries (incompatible), mod:friendsandfoes (incompatible), mod:farmersdelight, mod:culturaldelights (incompatible), mod:repurposed_structures, mod:terrablender, mod:moonlight (incompatible), mod:spelunkery (incompatible), mod:regions_unexplored (incompatible), mod:geode, mod:culllessleaves, mod:wthit (incompatible), mod:cnb, mod:farmersrespite (incompatible), mod:flywheel (incompatible), mod:create, mod:suppsquared (incompatible), mod:croptopia (incompatible), mod:lostcities (incompatible), mod:architectury (incompatible), mod:doapi (incompatible), mod:bakery (incompatible), mod:vinery, mod:nethervinery (incompatible), mod:meadow, mod:ferritecore (incompatible), mod:extradelight, mod:l2library (incompatible), mod:letmedespawn (incompatible), mod:delightful (incompatible), mod:geckolib3 (incompatible), mod:crittersandcompanions (incompatible), mod:fruitsdelight, mod:caupona (incompatible), Spelunkery Generated Pack, Supplementaries Generated Pack, Suppsquared Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-43.3.5
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		THT-1.19.2-4.3.1.jar                              |Tan's Huge Trees              |tht                           |4.3.1               |DONE      |Manifest: NOSIGNATURE
		habitat-1.2.4.jar                                 |Habitat                       |habitat                       |1.2.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1018.jar                  |Just Enough Items             |jei                           |11.6.0.1018         |DONE      |Manifest: NOSIGNATURE
		Galosphere-1.19.2-1.3.0-Forge.jar                 |Galosphere                    |galosphere                    |1.19.2-1.3.0        |DONE      |Manifest: NOSIGNATURE
		paragon-forge-3.0.2-1.19x.jar                     |Paragon                       |paragon                       |3.0.2               |DONE      |Manifest: NOSIGNATURE
		Structory_Towers_1.19.3_v1.0.2.jar                |Structory: Towers             |structorytowers               |1.0.2               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.2.jar                 |Waystones                     |waystones                     |11.4.2              |DONE      |Manifest: NOSIGNATURE
		badpackets-forge-0.2.3.jar                        |Bad Packets                   |badpackets                    |0.2.3               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |DONE      |Manifest: NOSIGNATURE
		gemsnjewels-1.19.2-0.2.1.jar                      |Gems & Jewels                 |gemsnjewels                   |0.2.1               |DONE      |Manifest: NOSIGNATURE
		twigs-forge-1.19.2-3.0.1.jar                      |Twigs                         |twigs                         |1.19.2-3.0.1        |DONE      |Manifest: NOSIGNATURE
		starlight-1.1.1+forge.cf5b10b.jar                 |Starlight                     |starlight                     |1.1.1+forge.a3aea74 |DONE      |Manifest: NOSIGNATURE
		molten_vents-1.19.2-2.0.4.jar                     |Molten Vents                  |molten_vents                  |2.0.4               |DONE      |Manifest: NOSIGNATURE
		bygonenether-1.3.2-1.19.2.jar                     |Bygone Nether                 |bygonenether                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.6.0.jar                       |Balm                          |balm                          |4.6.0               |DONE      |Manifest: NOSIGNATURE
		memoryleakfix-forge-1.17+-1.0.0.jar               |Memory Leak Fix               |memoryleakfix                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.3.5-universal.jar                 |Forge                         |forge                         |43.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ctov-3.2.6c.jar                                   |ChoiceTheorem's Overhauled Vil|ctov                          |3.2.6c              |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.4.13.jar                 |Supplementaries               |supplementaries               |1.19.2-2.4.13       |DONE      |Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.19.2-2.0.4.jar           |Friends&Foes                  |friendsandfoes                |2.0.4               |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		culturaldelights-1.19.2-0.15.4.jar                |Cultural Delights             |culturaldelights              |0.15.4              |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-6.3.28+1.19.2.jar     |Repurposed Structures         |repurposed_structures         |6.3.28+1.19.2       |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.166.jar           |TerraBlender                  |terrablender                  |2.0.1.166           |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.3.5-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.3.5        |DONE      |Manifest: NOSIGNATURE
		spelunkery-1.19.2-0.2.6-forge.jar                 |Spelunkery                    |spelunkery                    |1.19.2-0.2.6        |DONE      |Manifest: NOSIGNATURE
		RegionsUnexploredForge-0.5.3+1.19.2.jar           |Regions Unexplored            |regions_unexplored            |0.5.3               |DONE      |Manifest: NOSIGNATURE
		geodeforge-1.1.8-1.19.2.jar                       |Geode+                        |geode                         |1.1.8               |DONE      |Manifest: NOSIGNATURE
		CullLessLeaves-Reforged-1.0.5.jar                 |Cull Less Leaves Reforged     |culllessleaves                |1.0.5               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-5.19.3.jar                            |wthit                         |wthit                         |5.19.3              |DONE      |Manifest: NOSIGNATURE
		CNB-1.19-1.5.4.jar                                |Creatures and Beasts          |cnb                           |1.5.4               |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.19-2.0.jar                       |Farmer's Respite              |farmersrespite                |1.19-2.0            |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.10-20.jar               |Flywheel                      |flywheel                      |0.6.10-20           |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		suppsquared-1.19.2-1.1.1.jar                      |Supplementaries Squared       |suppsquared                   |1.19.2-1.1.1        |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |DONE      |Manifest: NOSIGNATURE
		lostcities-1.19-6.0.19.jar                        |LostCities                    |lostcities                    |1.19-6.0.19         |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |DONE      |Manifest: NOSIGNATURE
		doapi-1.1.0b.jar                                  |Lets Do Api                   |doapi                         |1.1.0b              |DONE      |Manifest: NOSIGNATURE
		letsdo-bakery-forge-1.0.6.jar                     |Bakery                        |bakery                        |1.0.6               |DONE      |Manifest: NOSIGNATURE
		letsdo-vinery-forge-1.3.12b.jar                   |Vinery                        |vinery                        |1.3.12              |DONE      |Manifest: NOSIGNATURE
		letsdo-nethervinery-forge-1.0.1.jar               |Nether Vinery                 |nethervinery                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		letsdo-meadow-forge-1.2.4.jar                     |Meadow                        |meadow                        |1.2.4               |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		extradelight-1.1.9.jar                            |ExtraDelight                  |extradelight                  |1.1.9               |DONE      |Manifest: NOSIGNATURE
		l2library-1.9.4.jar                               |L2 Library                    |l2library                     |1.9.4               |DONE      |Manifest: NOSIGNATURE
		letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar        |Let Me Despawn                |letmedespawn                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		Delightful-1.19.2-3.4.1.jar                       |Delightful                    |delightful                    |3.4.1               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |DONE      |Manifest: NOSIGNATURE
		crittersandcompanions-1.19.2-2.1.0.jar            |Critters and Companions       |crittersandcompanions         |1.19.2-2.1.0        |DONE      |Manifest: NOSIGNATURE
		fruitsdelight-0.5.2.jar                           |Fruits Delight                |fruitsdelight                 |0.5.2               |DONE      |Manifest: NOSIGNATURE
		caupona-1.19.2-0.2.7.jar                          |Caupona                       |caupona                       |1.19.2-0.2.7        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f617a0ce-d0be-4488-b5ef-a958d9d367dc
	FML: 43.3
	Forge: net.minecraftforge:43.3.5
	Flywheel Backend: GL33 Instanced Arrays

**Comment by KirboSoftware** [comment]
Thanks for bringing this up to us. We will be looking into this issue :+1: Please be patient :smile:

**Comment by UHQ-GAMES** [comment]
closing this since 1.19.2 versions are discontinued
